### PR TITLE
Tooth inventory

### LINKED ISSUE #46: Primary skeletal inventory for teeth
Create a primary skeletal inventory for teeth.

### PR DESCRIPTION
**Pull request by cuboideum**
This fixes #46. @MasterChief13, @kdaveed and @zarquon42b please read the following and give feedback.

The following structure for primary dental inventories is implemented:

rdfbones-o_dentalinventory

There are some issues with this layout, as it changes the general structure of [skeletal inventories](https://github.com/RDFBones/RDFBones-O/wiki/Skeletal-inventories) as specified before.

### Not all measurement values contained in the data set refer to segments of skeletal elements (class :SegmentOfSkeletalElement)

Class :ToothPosition is subclass of class obo:FMA_84926 ('Anatomical compartment space'). This decision was discussed in the project meeting on 24 January 2017. It implies that the class is not a subclass of :SegmentOfSkeleltalElement, although current documentation states that all measurement data in a skeletal inventory refer to one of its subclasses. As tooth positions are composed of two skeletal elements, it would not make sense to make them a subclass, although this would solve the problem.

*From the viewpoint of software integration, does it matter if not all measurement data refer to subclasses of :SegmentOfSkeletalElement?*

### Tooth positions are not regional parts of skeletal elements

So far, all measurement data in skeletal inventories follow the same structure:

1. they are about some segment of a skeletal element
2. the segment is a regional part of some skeletal element

Tooth positions, on the contrary, are composed of two skeletal elements and, therefore, violate this pattern. Writing queries on inventory data becomes more complex.

### Superclass for :Closure2States and :Expression2States

So far, authors of inventory extensions can add measurement data of types :CompletenessDatum or :TaphonomicStateDatum. The classes :Closure2States and :Expression2States do not fall into either of these categories. But in order to keep a uniform structure with all skeletal inventories, a superclass would be helpful. Both concepts describe qualities that are inherent to the object itself and that were formed by natural forces.

*Philosophers to the fore: How should the superclass be named?*

## Approaches to a solution

The precondition that skeletal inventory measurement data should always refer to segments of skeletal elements is mostly necessary for completeness data, as from them it should be possible to aggregate completeness of skeletal elements on bone level. With the other types, it would suffice if they all refer to concepts that have some partonomic relation to skeletal elements.

We could make :SegmentOfSkeletalElement a subclass of obo:FMA_84926 ('Anatomical compartment space') and prescribe that all measurement data have to refer to some anatomical compartment space or, to make it more flexible, to a subclass of obo:FMA_67112 ('Immaterial anatomical entity') - which is a superclass of obo:FMA_84926 ('Anatomical compartment space'). Only for measurement data of type :CompletenessDatum it is necessary to refer to a subclass of :SegmentOfSkeletalElement.

*Please let me know if you think that this would contribute towards a clearer definition of skeletal inventories.*

### CODE REVIEW

**Comment by cuboideum** [comment]
@MasterChief13: Thanks for the detailed response. Here are some answers to questions you put forward.

## Answers to observed problems

1. You are right. But this is an up-stream issue with the OBO-version of the FMA. We already found this out last year (cf. [comment](https://github.com/RDFBones/RDFBones-O/issues/28#issuecomment-226501074) to #28), but it seems to be fixed in the better-supported FMAInOwl version (cf. [comment](https://github.com/RDFBones/RDFBones-O/issues/28#issuecomment-226713201)).

2. No, they do not exist twice. But they have two superclasses, one specifying the type of information they are carrying (closure, expression or completeness) and another specifying their data structure ('Categorical measurement datum'). The first is needed in queries for specific types of information, the other to specify how queries need to be structured in order to retrieve information. In RDF, it is possible to define several superclasses that are not subclasses of each other, although at the risk of circular inferences.

3. I think you misinterpret the meaning of the class. Non-expression implies that a grown-up individual is lacking one tooth from the standard dentition in its secondary dentition. The sole purpose of the class is to give researchers the opportunity to state that a certain tooth never existed, as opposed to lost either pre- or postmortem. In order to assess tooth expression, the neighbouring positions need to contain secondary teeth.

4. No, just as primary skeletal inventories, primary dental inventories are not presumed to represent individuals. You can use them to record a collection of mixed individual teeth. However, as with skeletal subdivisions, if they are recorded to belong to the same dental arcade, this implies that they belong to the same individual. You are right to point out that in this case a relationship to a maxilla or mandible should be specified. I have added this functionality in commit 6959d50d36865d75e1f51b8fa0e33df65c1882c2.

5. The range statements are necessary to define cardinalities in a way that VITRO understands (it does not validate more complex OWL statements). So far, we have not experienced performance issues related to cardinality statements - probably because VITRO does not evaluate them, anyway.

6. In anatomy, right and left are always understood from the individual's point of view, i.e. the right arm is a person's right arm.

## Answers to concluding remarks

> Intravital or postmortal tooth loss can be answered naively by referring to closed or open sockets (maybe you need a separate extension for that).

Yes, that is how it is normally done. But this is not an issue with dental inventories. As you say, it has to be determined in the extension.

> In case of hypo-dontia, there is a closed socket, a not expressed tooth position and no related instance of :EntireTooth. This indicates hypo-dontia or intravital tooth loss. On the basis of this tooth inventory you cannot distinguish these cases.

No, it is only hypodontia if the tooth position is not expressed. Only a socket that has existed at some point in time can be closed. Hypodontia can only be diagnosed if the adjacent positions are preserved (cf. above). If a lot of sockets are closed, it might be difficult or even impossible to recognise hypodontia. A position is only marked as expressed or non-expressed if this is evident from the material. If this is not the case, no information is given.

> But how can we handle teeth which were excavated from one single grave but which do not fit in any tooth socket?

Just as with skeletal elements, you can enter single teeth without any relation to a position or dental arcade.

**Comment by cuboideum** [comment]
This drawing illustrates the relations between dental and skeletal inventories, introduced in commit 6959d50d36865d75e1f51b8fa0e33df65c1882c2:

rdfbones-o_linkdentalinventoryskeletalinventory

The relations would be more concise if the subclass-relations between the dental arcade classes would be correct. But this will automatically resolved once we change from the OBO-version of the FMA to the FMAInOwl version.

**Comment by kdaveed** [comment]
From your discussion and from issue https://github.com/RDFBones/RDFBones-O/issues/46 I would design the following entry form layout:

screen shot 2017-02-22 at 22 42 18

After adding any tooth, the following subform would appear:

screen shot 2017-02-22 at 22 42 48

which allows to select the closure, expression and completeness states for the added tooth.

The data storage then would look like as follows:


screen shot 2017-02-22 at 22 55 46


Where the green nodes denotes the variables from the form. The blue stands for the dental skeletal inventory, from whose profile page the entry form was loaded. The white nodes are the classes, whose URI can be evaluated by SPARQL queries performed on the ontology.
The most important input variable is the _?toothUri_. This represents the added tooth. The three state variables are just like as by the normal skeletal inventories.

**Comment by cuboideum** [comment]
This pull request is outdated because of an improved concept presented in #46 (in this [comment](https://github.com/RDFBones/RDFBones-O/issues/46#issuecomment-291491422)). A new pull request will implement this concept.

**Pull request closed without merging**
